#!/bin/bash

echo Regenerating ssh keys...
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server

# Don't run this script again.
# If the LVM step below fails, don't retry because we might wipe real data.
rm -f /etc/rcS.d/S10firstboot

echo Extending root partition to 3GB...
# Note: start sector must match value in build.sh
sfdisk --no-reread /dev/mmcblk0 <<EOF
# partition table of /dev/mmcblk0
unit: sectors

/dev/mmcblk0p1 : start=     2048, size=   262144, Id= c
/dev/mmcblk0p2 : start=   264192, size=  6291455, Id=83
EOF
partprobe
resize2fs /dev/mmcblk0p2

echo Creating LVM partition...
# In case there's one already:
lvchange -an vg0
# Not really "ext4", but lvm isn't an option:
parted /dev/mmcblk0 --script -- mkpart primary ext4 6555648s -1s
parted /dev/mmcblk0 --script -- set 3 lvm on
pvcreate -ffy /dev/mmcblk0p3
vgcreate vg0 /dev/mmcblk0p3
vgs

echo Starting Xen
# Needed for Xenstore and /proc/xen
/etc/init.d/xen start

echo Configuring xapi
SERVICES="message-switch forkexecd xcp-networkd xcp-rrdd xenopsd-xenlight xapi-storage-script squeezed xapi"
for i in $SERVICES; do
  echo Setting $i to start on default runlevels
  update-rc.d $i defaults
  echo Starting $i immediately
  service $i start
done

echo Waiting for Xapi to start responding
RETRIES=60
while [ ${RETRIES} -ne 0 ]; do
  ENABLED=$(xe host-list params=enabled --minimal 2>/dev/null)
  if [ "${ENABLED}" = "true" ]; then
    echo Xapi startup complete
    RETRIES=0
  else
    sleep 1
    echo -n .
    RETRIES=$(( ${RETRIES} - 1 ))
  fi
done

echo Creating a thin-LVM SR on flash
HOST=$(xe host-list params=uuid --minimal)
# There's a bug causing this to fail
SR=$(xe sr-create name-label="thin-provisioned LVM" host-uuid=$HOST type=ezlvm device-config:uri=vg:///vg0)
SR=$(xe sr-list type=ezlvm params=uuid --minimal)
POOL=$(xe pool-list params=uuid --minimal)
xe pool-param-set uuid=$POOL default-SR=$SR crash-dump-SR=$SR suspend-image-SR=$SR

echo Setting the network configuration
HOST=$(xe host-list params=uuid --minimal)
xe pif-scan host-uuid=$HOST
PIF=$(xe pif-list device=eth0 params=uuid --minimal)
xe pif-reconfigure-ip uuid=$PIF mode=dhcp
xe pif-plug uuid=$PIF
xe host-management-reconfigure pif-uuid=$PIF
xe pool-sync-database

echo Setup complete
