#!/bin/bash

echo Regenerating ssh keys...
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server

# Don't run this script again.
# If the LVM step below fails, don't retry because we might wipe real data.
rm -f /etc/rcS.d/S10firstboot

echo Extending root partition to 3GB...
# Note: start sector must match value in build.sh
sfdisk --no-reread /dev/mmcblk0 <<EOF
# partition table of /dev/mmcblk0
unit: sectors

/dev/mmcblk0p1 : start=     2048, size=   262144, Id= c
/dev/mmcblk0p2 : start=   264192, size=  6291455, Id=83
EOF
partprobe
resize2fs /dev/mmcblk0p2

echo Creating LVM partition...
# In case there's one already:
lvchange -an vg0
# Not really "ext4", but lvm isn't an option:
parted /dev/mmcblk0 --script -- mkpart primary ext4 6555648s -1s
parted /dev/mmcblk0 --script -- set 3 lvm on
pvcreate -ffy /dev/mmcblk0p3
vgcreate vg0 /dev/mmcblk0p3
vgs
